### ISSUE TITLE
Integration Entity Unavailable 

### ISSUE THREAD

**Issue by daviss57** [jasonmadigan/ha-hkc#10]
After installation the entity remains unavailable. 

![Screenshot_20231226_112723_Home Assistant](https://github.com/jasonmadigan/ha-hkc/assets/65281157/eee24440-2489-4df7-87c5-30fe9c3b1932)
![Screenshot_20231226_112139_Home Assistant](https://github.com/jasonmadigan/ha-hkc/assets/65281157/8ee622c2-7e0e-41ef-8940-fbbf188f0caa)

**Comment by jasonmadigan** [comment]
Can you double check the panel ID, panel password and pin are correct? The panel ID and password will be the ones you use to login to the HKC app.

**Comment by daviss57** [comment]
> Can you double check the panel ID (sometimes referred to as site ID), panel password and pin are correct? The panel/site ID and password will be the ones you use to login to the HKC app.

Hi,checked both. I have also installed at another site and had the same issue. Not sure how exactly I can debug.

**Comment by daviss57** [comment]
Would it be anything to do with the fact that my communication board is both GSM and WIFI? Would not have thought so but failing to identify the issue.

**Comment by jasonmadigan** [comment]
@daviss57 no problem, and thanks for the logs. The `Unable to find services.yaml for the hkc_alarm integration` is a bit of a red herring that we can ignore (will be fixed later). The status fetching logs themselves look pretty healthy, so something else might be up.

Just thinking: what kind of alarm configuration do you have in terms of arming states? Is it a normal config with arm home / partset / disarm?

**Comment by daviss57** [comment]
Yep standard configuration, arm (everyone out), Partset A  (nighttime), dissarm

**Comment by daviss57** [comment]
Monitored over the last number of days. No new entries, all fetching seems to be successfull but still appears unavailable. Not sure where or what to look at next.

**Comment by jasonmadigan** [comment]
If you've got some Python skills, you could give the Example Usage section of the pyhkc lib (used by this integration) a try to see if it can read inputs:

https://github.com/jasonmadigan/pyhkc

**Comment by daviss57** [comment]
> If you've got some Python skills, you could give the Example Usage section of the pyhkc lib (used by this integration) a try to see if it can read inputs:
> 
> https://github.com/jasonmadigan/pyhkc

Unfortunately my Phython Skils are not up to that at the moment.

**Comment by daviss57** [comment]
Hi Jason, Did you ever get a chance to look into this a little more?

I was trying ou the Example Usage but I'm not sure I am on the right track.
