### ISSUE TITLE
Stauts keeps flicking between Armed and Disarmed

### ISSUE THREAD

**Issue by daviss57** [jasonmadigan/ha-hkc#22]
When the system is armed at night the status keeps flicking between Armed Home and Disarmed.

It does not seem to occur when the system is disarmed, only really when the system is in any of the Armed states i.e. Armed away or Armed Home.

See log below

24 June 2024
HKC Alarm System changed to Disarmed
06:24:49 - 3 hours ago
HKC Alarm System changed to Armed home
06:22:49 - 3 hours ago
HKC Alarm System changed to Disarmed
05:45:33 - 3 hours ago
HKC Alarm System changed to Armed home
05:44:27 - 3 hours ago
HKC Alarm System changed to Disarmed
05:42:20 - 4 hours ago
HKC Alarm System changed to Armed home
05:40:20 - 4 hours ago
HKC Alarm System changed to Disarmed
05:37:38 - 4 hours ago
HKC Alarm System changed to Armed home
05:36:35 - 4 hours ago
HKC Alarm System changed to Disarmed
05:31:26 - 4 hours ago
HKC Alarm System changed to Armed home
05:30:21 - 4 hours ago
HKC Alarm System changed to Disarmed
05:21:54 - 4 hours ago
HKC Alarm System changed to Armed home
05:20:48 - 4 hours ago
HKC Alarm System changed to Disarmed
05:18:41 - 4 hours ago
HKC Alarm System changed to Armed home
05:17:34 - 4 hours ago
HKC Alarm System changed to Disarmed
05:07:15 - 4 hours ago
HKC Alarm System changed to Armed home
05:05:14 - 4 hours ago
HKC Alarm System changed to Disarmed
05:00:13 - 4 hours ago
HKC Alarm System changed to Armed home
04:59:06 - 4 hours ago
HKC Alarm System changed to Disarmed
04:48:12 - 4 hours ago
HKC Alarm System changed to Armed home
04:44:39 - 4 hours ago
HKC Alarm System changed to Disarmed
04:43:34 - 4 hours ago
HKC Alarm System changed to Armed home
04:42:29 - 5 hours ago
HKC Alarm System changed to Disarmed
04:04:14 - 5 hours ago
HKC Alarm System changed to Armed home
04:02:14 - 5 hours ago
HKC Alarm System changed to Disarmed
04:01:00 - 5 hours ago
HKC Alarm System changed to Armed home
03:59:54 - 5 hours ago
HKC Alarm System changed to Disarmed
03:56:15 - 5 hours ago
HKC Alarm System changed to Armed home
03:55:05 - 5 hours ago
HKC Alarm System changed to Disarmed
03:43:07 - 5 hours ago
HKC Alarm System changed to Armed home
03:41:07 - 6 hours ago
HKC Alarm System changed to Disarmed
03:40:07 - 6 hours ago
HKC Alarm System changed to Armed home
03:38:07 - 6 hours ago
HKC Alarm System changed to Disarmed
03:34:56 - 6 hours ago
HKC Alarm System changed to Armed home
03:33:48 - 6 hours ago
HKC Alarm System changed to Disarmed
03:30:39 - 6 hours ago
HKC Alarm System changed to Armed home
03:28:38 - 6 hours ago
HKC Alarm System changed to Disarmed
03:24:30 - 6 hours ago
HKC Alarm System changed to Armed home
03:22:29 - 6 hours ago
HKC Alarm System changed to Disarmed
03:10:00 - 6 hours ago
HKC Alarm System changed to Armed home
03:05:52 - 6 hours ago
HKC Alarm System changed to Disarmed
03:03:23 - 6 hours ago
HKC Alarm System changed to Armed home
03:02:18 - 6 hours ago
HKC Alarm System changed to Disarmed
02:49:18 - 6 hours ago
HKC Alarm System changed to Armed home
02:47:17 - 7 hours ago
HKC Alarm System changed to Disarmed
02:22:14 - 7 hours ago
HKC Alarm System changed to Armed home
02:19:09 - 7 hours ago
HKC Alarm System changed to Disarmed
01:54:13 - 7 hours ago
HKC Alarm System changed to Armed home
01:53:06 - 7 hours ago
HKC Alarm System changed to Disarmed
01:48:59 - 7 hours ago
HKC Alarm System changed to Armed home
01:45:25 - 8 hours ago
HKC Alarm System changed to Disarmed
01:40:25 - 8 hours ago
HKC Alarm System changed to Armed home
01:38:25 - 8 hours ago
HKC Alarm System changed to Disarmed
00:57:18 - 8 hours ago
HKC Alarm System changed to Armed home
00:53:56 - 8 hours ago

**Comment by jasonmadigan** [comment]
I am seeing similar. HKC's been experiencing a huge outage since yesterday evening: https://www.boards.ie/discussion/2058353965/new-hkc-app-securecomm2/p2

Cloud responses have been broken/intermittent since. This should resolve after they resolve their issues.

**Comment by daviss57** [comment]
Not a new issue, has been like this for some time. Just took today and yesterday as an example. The below is from a date last week.

HKC Alarm System changed to Disarmed
08:23:32 - 2 weeks ago
HKC Alarm System changed to Armed away
08:04:00 - 2 weeks ago
HKC Alarm System changed to Disarmed
08:02:59 - 2 weeks ago
HKC Alarm System changed to Armed away
04:00:58 - 2 weeks ago
HKC Alarm System changed to Disarmed
03:59:57 - 2 weeks ago
HKC Alarm System changed to Armed away
01:44:33 - 2 weeks ago
HKC Alarm System changed to Disarmed
01:43:27 - 2 weeks ago
HKC Alarm System changed to Armed away
01:14:00 - 2 weeks ago
HKC Alarm System changed to Disarmed
01:12:59 - 2 weeks ago
HKC Alarm System changed to Armed away
00:20:14 - 2 weeks ago
HKC Alarm System changed to Disarmed
00:19:13 - 2 weeks ago
HKC Alarm System changed to Armed away
00:17:09 - 2 weeks ago
HKC Alarm System changed to Disarmed
00:16:08 - 2 weeks ago

**Comment by jasonmadigan** [comment]
This should be fixed by https://github.com/jasonmadigan/ha-hkc/releases/tag/1.0.15
