### ISSUE TITLE
Integration failing to complete start-up

### ISSUE THREAD

**Issue by hughjohns** [jasonmadigan/ha-hkc#31]
Apologies if I am covering anything that is already fixed bit of a newbie and trying to learn

Integration fails to start after HA update, appeared to be fine until August core update.

Have checked on 1 of the closed issues for error 400 but all the code changes appear to match the updated version

Log attached
[home-assistant_2024-09-05T12-27-21.643Z.log](https://github.com/user-attachments/files/16893431/home-assistant_2024-09-05T12-27-21.643Z.log)

**Comment by jasonmadigan** [comment]
Hi @hughjohns - do you know if your HKC install includes a WiFi card for state syncing? If it's only using GSM, this integration shouldn't be used (HKC seem have a rate limit for the amount of calls the GSM card can sync per month).

**Comment by daviss57** [comment]
Same issue here, working fine at home. Was trying to setup similar for my Parents on their HA setup. Keep getting "Unknown Error Occurred". Been like this for a while.
Also tried adding their alarm to my HA instance to see if it was something with their setup but same issue.

**Comment by jasonmadigan** [comment]
> Same issue here, working fine at home. Was trying to setup similar for my Parents on their HA setup. Keep getting "Unknown Error Occurred". Been like this for a while. Also tried adding their alarm to my HA instance to see if it was something with their setup but same issue.

Is it the same though? Did the integration ever work?

Without logs, the main cause of Unknown Error Occurred is an auth failure:

Panel ID: Your HKC Alarm Panel ID (same as panel ID in HKC mobile app)
Panel Password: Your HKC Alarm Panel Password (same as panel password from HKC mobile app - this is NOT your alarm pin)
Alarm Code: Your HKC Alarm Code/PIN

**Comment by hughjohns** [comment]
Hi All, not sure what the full resolution was but integration is now working, it would appear to be down to a ISP router update that has required to me to have to open port for incoming access to the panel, as I subsequently found out that the official app failed to log onto the panel even though I was getting the set & unsent to my phone. The install engineer gave me this information last night so I have implemented that this morning and as of now all appears to work, port 50001 if that potentially helps. thank you for looking into this.

**Comment by hughjohns** [comment]
> Hi @hughjohns - do you know if your HKC install includes a WiFi card for state syncing? If it's only using GSM, this integration shouldn't be used (HKC seem have a rate limit for the amount of calls the GSM card can sync per month).

HI @jasonmadigan , just for reference yes WiFi sync, I have now closed as appears sorted.
