### ISSUE TITLE
Question - HKC Models

### ISSUE THREAD

**Issue by Infeconex** [jasonmadigan/ha-hkc#33]
Just a question about which HKC Panels are supported. Does this include current panels.

Also, for the polling interval, does this mean movement sensors would be up to 60 seconds delayed?

**Comment by jasonmadigan** [comment]
> Just a question about which HKC Panels are supported. Does this include current panels.

I don't have a list, but pretty much any panel that works with the SecureComm v2 app should work fine.

> Also, for the polling interval, does this mean movement sensors would be up to 60 seconds delayed?

Yes
