### ISSUE TITLE
Access to the log entries from HomeAssistant

### ISSUE THREAD

**Issue by ac931274** [jasonmadigan/ha-hkc#35]
Hello there,
First of all, thanks for this integration, it will help us a lot, were are using it and HomeAssistant to manage a community hall.
Could you add the functionality to pull back the log entries from the Alarm System? I can see from the hkc_api.py module that you wrote that it is capable of pulling the logs back.  My end goal is to be able to trace WHO unset and set the alarm system.  I know when I look in the app, it says Set / Unset by User X.  

Thanks in advance.

Jonathan

**Comment by jasonmadigan** [comment]
Will have a think about this.

In the meantime, if you like to tinker, `pyhkc` itself can read logs:

https://github.com/jasonmadigan/pyhkc
```
...
# View recent logs.
logs = alarm_system.fetch_logs()
print("Recent Logs:", logs)
```

To integrate, consider creating a Python Script, i.e.:

https://www.home-assistant.io/integrations/python_script/

- Create a script that does much the same as the example script (probably only outputting the logs in your case).
- Then use a [Command Line sensor](https://www.home-assistant.io/integrations/command_line/) to call the script, and do something with the output (e.g. parse the logs, use them as values for some custom sensor)

HTH
